name: iOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test iOS App
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_15.4.app/Contents/Developer

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Show SDK Location
      run: xcodebuild -showsdks

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project hellotetris.xcodeproj \
          -scheme hellotetris \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
